### ISSUE TITLE
Multiple Domains

### ISSUE THREAD

**Issue by mskian** [dyaa/node-ssl-checker#18]
Hi is this possible to Check Multiple Domains?

```js
sslChecker('example1.com','example2.com', 'GET', 443)`
```
another Suggestion include domain name in JSON output

**Comment by dyaa** [comment]
Hi @mskian, 

The whole idea being this module is using NodeJS's [getPeerCertificate](https://nodejs.org/api/tls.html#tls_tlssocket_getpeercertificate_detailed), Which means we call the server/domain to get these details!

Adding more domains will mean having longer time to receive the payload data, So instead I'd make two calls instead of supporting multiple domains!

> another Suggestion include domain name in JSON output

Good idea, to be added soon!

-----

Any more ideas you'll like to see in the next version?

**Comment by dyaa** [comment]
I'll mark this issue as closed, Feel free to re-open it 😉
